/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.qubo.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQUBOScopeProvider extends DelegatingScopeProvider {
}
