/*
 * generated by Xtext 2.26.0
 */
package qubo.lang.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class QUBOProposalProvider extends AbstractQUBOProposalProvider {
}
