/*
 * generated by Xtext 2.31.0
 */
package quantum.circuit.lang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import quantum.circuit.lang.parser.antlr.internal.InternalQuCircuitParser;
import quantum.circuit.lang.services.QuCircuitGrammarAccess;

public class QuCircuitParser extends AbstractAntlrParser {

	@Inject
	private QuCircuitGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQuCircuitParser createParser(XtextTokenStream stream) {
		return new InternalQuCircuitParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "QuantumCircuit";
	}

	public QuCircuitGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QuCircuitGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
