/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.qubo.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QUBOAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/jku/se/qubo/lang/parser/antlr/internal/InternalQUBO.tokens");
	}
}
