/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.qubo.lang.ide;

import at.jku.se.qubo.lang.QUBORuntimeModule;
import at.jku.se.qubo.lang.QUBOStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QUBOIdeSetup extends QUBOStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QUBORuntimeModule(), new QUBOIdeModule()));
	}
	
}
