/*
 * generated by Xtext 2.26.0
 */
package qubo.lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QUBORuntimeModule extends AbstractQUBORuntimeModule {
}
