/*
 * generated by Xtext 2.31.0
 */
package quantum.circuit.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuCircuitScopeProvider extends DelegatingScopeProvider {
}
