/*
 * generated by Xtext 2.26.0
 */
package qubo.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QUBOUiModule extends AbstractQUBOUiModule {

	public QUBOUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
