/*
 * generated by Xtext 2.26.0
 */
package qubo.lang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import qubo.lang.ui.internal.LangActivator;

public class QUBOUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("qubo.lang.QUBO");
	}

}
