/*
 * generated by Xtext 2.26.0
 */
package quantum.circuit.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QuCircuitStandaloneSetup extends QuCircuitStandaloneSetupGenerated {

	public static void doSetup() {
		new QuCircuitStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
