/*
 * generated by Xtext 2.26.0
 */
package quantum.circuit.lang;

import org.eclipse.xtext.linking.ILinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuCircuitRuntimeModule extends AbstractQuCircuitRuntimeModule {
	
	@Override
	public Class<? extends ILinker> bindILinker() {
		return QuantumCircLinker.class;
	}
	
}
