/*
 * generated by Xtext 2.26.0
 */
package quantum.circuit.lang.scoping;

import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider;

import com.google.inject.Inject;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class QuCircuitScopeProvider extends AbstractQuCircuitScopeProvider {
	
		
}
