/*
 * generated by Xtext 2.26.0
 */
package quantum.circuit.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QuCircuitUiModule extends AbstractQuCircuitUiModule {

	public QuCircuitUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
