/*
 * generated by Xtext 2.26.0
 */
package qubo.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;

import qubo.lang.QUBORuntimeModule;
import qubo.lang.QUBOStandaloneSetup;

import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QUBOIdeSetup extends QUBOStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QUBORuntimeModule(), new QUBOIdeModule()));
	}
	
}
