/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.qubo.lang.validation;

import org.eclipse.xtext.validation.Check;

import at.jku.se.qubo.mm.qubo.Matrix;
import at.jku.se.qubo.mm.qubo.QuboPackage;
import at.jku.se.qubo.mm.qubo.Row;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class QUBOValidator extends AbstractQUBOValidator {
	
	@Check
	public void checkMatrixUppperHalf(Matrix matrix) {
		//Number of columns of the first Row
		int numberOfColumns = matrix.getRows().size();
		for (Row row : matrix.getRows()) {
			if (row.getColumns().size() != numberOfColumns) {
				error("The size of this columns must be equal to: " + numberOfColumns, row, QuboPackage.Literals.ROW__COLUMNS);
			}
			//Reduce the number of rows
			numberOfColumns--;
		}
	}
	
}
