/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.qubo.lang.validation;

import java.util.stream.Collectors;

import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;

import at.jku.se.qubo.mm.qubo.Matrix;
import at.jku.se.qubo.mm.qubo.QuboPackage;
import at.jku.se.qubo.mm.qubo.Row;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class QUBOValidator extends AbstractQUBOValidator {
	
	@Check
	public void checkGreetingStartsWithCapital(Matrix matrix) {
		int numberOfRows = matrix.getRows().size();
		EList<Row> rows = matrix.getRows()
							.stream()
							.filter(r -> r.getColumns().size() != numberOfRows)
							.collect(Collectors.toCollection(BasicEList::new))
							;
		for (Row row : rows) {
			error("The size of this columns must be equal to: " + numberOfRows, row, QuboPackage.Literals.ROW__COLUMNS);
		}
	}
	
}
